// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using opendataws.data.Context;

#nullable disable

namespace opendataws.data.Migrations
{
    [DbContext(typeof(EnvironmentContext))]
    [Migration("20230102113525_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("opendataws.entity.Entities.EnvironmentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Basinc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstasyonAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IstasyonNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayıtTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pm10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pm25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sicaklik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnvironmentData");
                });
#pragma warning restore 612, 618
        }
    }
}
