using System;
using System.Collections.Generic;

namespace opendataws.data.CbsModel
{
    public partial class CbsImarKiraTasinmazFlex
    {
        public double? AylikKira { get; set; }
        public string? BaslamaTarihi { get; set; }
        public string? BitisTarihi { get; set; }
        public double? DonemSayisi { get; set; }
        public string? GuncellemeTarihi { get; set; }
        public string? KayitTarihi { get; set; }
        public string? EncumenKararNo { get; set; }
        public string? EncumenKararTarihi { get; set; }
        public string? KdvOrani { get; set; }
        public double? Id { get; set; }
        public double? IdBkrGelir { get; set; }
        public double? IdSisKullaniciGuncelleyen { get; set; }
        public double? IdSisKullaniciKaydeden { get; set; }
        public double? Versiyon { get; set; }
        public double? IdBgsBeyan { get; set; }
        public string? IslemYapilanIp { get; set; }
        public double? IdEisTasinmaz { get; set; }
        public string? Ecrimisil { get; set; }
        public string? IdEisTasinmazGrup { get; set; }
        public string? MeclisKararTarihi { get; set; }
        public string? MeclisKararNo { get; set; }
        public string? OlurTarihi { get; set; }
        public string? OlurNo { get; set; }
        public string? FesihTarihi { get; set; }
        public string? FesihNo { get; set; }
        public string? MulkiyetDurumu { get; set; }
        public string? Icra { get; set; }
        public string? IdBkrFaaliyet { get; set; }
        public string? SozlesmeBedeli { get; set; }
        public string? IdEisKullanimYerleri { get; set; }
        public string? YonlendirilenIpListesi { get; set; }
        public string? BilaBedel { get; set; }
        public string? IsgalTarihi { get; set; }
        public string? IdBkrIsgalTuru { get; set; }
        public double? EcrimisilTahakkukTuru { get; set; }
        public string? ArsivNo { get; set; }
        public string? DosyaNo { get; set; }
        public double? IdKbsServis { get; set; }
        public string? Aciklama { get; set; }
        public string? KiraTahakkukTuru { get; set; }
        public string? IndirimMiktari { get; set; }
        public string? PesinOdemeMiktari { get; set; }
        public string? AylikFaizOrani { get; set; }
        public string? MekansalId { get; set; }
        public string? IsgalAlani { get; set; }
        public string? SureUzatimTarihi { get; set; }
        public string? SureUzatimiVarmi { get; set; }
        public string? IdBkrKullanimTuru { get; set; }
        public string? IdPbsPersonelSozlsmeYapan { get; set; }
        public double? Id1 { get; set; }
        public string? GuncellemeTarihi1 { get; set; }
        public string? KayitTarihi1 { get; set; }
        public string? Aciklama1 { get; set; }
        public double? BeyanNo { get; set; }
        public double? BeyanSira { get; set; }
        public string? BeyanTarihi { get; set; }
        public double? HissePay { get; set; }
        public double? HissePayda { get; set; }
        public string? KapamaTarihi { get; set; }
        public string? KapamaTuru { get; set; }
        public string? MukellefiyetBaslamaTarihi { get; set; }
        public string? TanzimTarihi { get; set; }
        public string? TarhiyatTuru { get; set; }
        public string? VermeNedeni { get; set; }
        public double? Versiyon1 { get; set; }
        public double? Yil { get; set; }
        public double? IdSisKullaniciGuncelleyen1 { get; set; }
        public double? IdSisKullaniciKaydeden1 { get; set; }
        public double? IdBgpServis { get; set; }
        public string? IdBgsBeyanOnceki { get; set; }
        public string? IdKbsFaaliyet { get; set; }
        public double? IdSbsMuhatap { get; set; }
        public string? EmlakTuru { get; set; }
        public string? VermeSekli { get; set; }
        public double? IdKbsAdres { get; set; }
        public string? IslemYapilanIp1 { get; set; }
        public string? YonlendirilenIpListesi1 { get; set; }
        public string? AktarmaId { get; set; }
        public string? ArsivDosyaNo { get; set; }
        public string? KapamaNedeni { get; set; }
        public string? BeyanKimlikNo { get; set; }
        public string? IdBgsBeyanOncekiDuzeltme { get; set; }
        public double? Id2 { get; set; }
        public string? GuncellemeTarihi2 { get; set; }
        public string? KayitTarihi2 { get; set; }
        public string? Isim { get; set; }
        public string? MuhatapTuru { get; set; }
        public double? Versiyon2 { get; set; }
        public string? IdSisKullaniciGuncelleyen2 { get; set; }
        public double? IdSisKullaniciKaydeden2 { get; set; }
        public string? Kentli { get; set; }
        public string? VergiDairesi { get; set; }
        public string? VergiMukellefi { get; set; }
        public string? VergiNo { get; set; }
        public string? KapamaTarihi1 { get; set; }
        public string? KapamaTuru1 { get; set; }
        public string? Aciklama2 { get; set; }
        public string? Muhasebe { get; set; }
        public double? AktarmaId1 { get; set; }
        public string? AktarmaIdSatin { get; set; }
        public string? Satinalma { get; set; }
        public string? IslemYapilanIp2 { get; set; }
        public string? UyariNotu { get; set; }
        public string? YonlendirilenIpListesi2 { get; set; }
        public double? MaliHizmetlerArsivNo { get; set; }
        public string? MersisNo { get; set; }
        public string? KayyumAtandi { get; set; }
        public string? EskiSicil { get; set; }
        public string? IlanReklamArsivNo { get; set; }
        public string? TicaretSicilMudurluk { get; set; }
        public string? TicaretSicilNo { get; set; }
    }
}
