using System;
using System.Collections.Generic;

namespace opendataws.data.CbsModel
{
    public partial class ViewItfaiyeYanginRaporu
    {
        public int? RaporUlasmadk { get; set; }
        public int? RaporMudahaledk { get; set; }
        public int? RaporYil { get; set; }
        public int? RaporAy { get; set; }
        public string? OlayinGorulduguDurum { get; set; }
        public string? OlayinGorulduguDurumTxt { get; set; }
        public string IhbarDurum { get; set; } = null!;
        public string SubeAdi { get; set; } = null!;
        public string PostaAdi { get; set; } = null!;
        public string? Adres { get; set; }
        public int Id { get; set; }
        public DateTime? OlayTarihi { get; set; }
        public string? BildirimSiraNo { get; set; }
        public DateTime? BildirimTarihi { get; set; }
        public string? BildirenKisiAdi { get; set; }
        public string? BildirenTel { get; set; }
        public int? BildirimAlanPersonel { get; set; }
        public string? BildirilenAdres { get; set; }
        public string? DogruAdres { get; set; }
        public int? YanginTuru { get; set; }
        public int? BinaYapimsekli { get; set; }
        public int? BinaKullanimSekli { get; set; }
        public string? Sahibi { get; set; }
        public string? KiraciVeyaKullanan { get; set; }
        public int? GidenEkibinAmiri { get; set; }
        public int? GidenEkibinAracSayisi { get; set; }
        public string? GidenEkibinPersonel { get; set; }
        public DateTime? GidenEkibinCikistarihi { get; set; }
        public DateTime? GidenEkibinVaristarihi { get; set; }
        public DateTime? GidenEkibinAyrilistarihi { get; set; }
        public DateTime? GidenEkibinDonustarihi { get; set; }
        public DateTime? ElektrikArizaGelistarihi { get; set; }
        public DateTime? AmbulansGelisTarihi { get; set; }
        public DateTime? DogalgazEkibiGelisTarihi { get; set; }
        public DateTime? YEkipCikistarihi { get; set; }
        public int? YEkipAracsayisi { get; set; }
        public string? YEkipPersonel { get; set; }
        public int? YEkipAmiri { get; set; }
        public int? SondurmeTuru { get; set; }
        public int? SondurmeSuMiktari { get; set; }
        public int? SondurmeKopukMiktari { get; set; }
        public int? SondurmeKktMiktari { get; set; }
        public string? HasarDurumu { get; set; }
        public int? YanginNedeni { get; set; }
        public string? YanginNedeniAciklama { get; set; }
        public string? SigortaSirketAdi { get; set; }
        public string? SigortaBedeli { get; set; }
        public string? AracGerecKaybi { get; set; }
        public string? YanginYeriTeslimEdilen { get; set; }
        public int? OluHayvanSayisi { get; set; }
        public int? YaraliHayvanSayisi { get; set; }
        public string? GidenEkipAdi { get; set; }
        public int? YanginNobetciCavusu { get; set; }
        public int? YanginNobetciAmiri { get; set; }
        public string? KayitUserId { get; set; }
        public int? GuncelleyenUserId { get; set; }
        public DateTime? GuncellemeTarihi { get; set; }
        public int? Turu { get; set; }
        public string? IhbarAciklamasi { get; set; }
        public int? Durum { get; set; }
        public int? BinaNo { get; set; }
        public int? KurtarmaTuru { get; set; }
        public string? BildirimAlanPersonelTxt { get; set; }
        public string? GidenEkibinAmiriTxt { get; set; }
        public string? YEkipAmiriTxt { get; set; }
        public string? YanginTuruTxt { get; set; }
        public string? BinaYapimsekliTxt { get; set; }
        public string? BinaKullanimSekliTxt { get; set; }
        public string? SondurmeTuruTxt { get; set; }
        public string? YanginNedeniTxt { get; set; }
        public string? TuruTxt { get; set; }
        public string? DurumTxt { get; set; }
        public string? KurtarmaTuruTxt { get; set; }
        public string? DogalAfetTuruTxt { get; set; }
        public string? YanginKurtarmaDogalafetTur { get; set; }
        public int? AsilsizIhbar { get; set; }
        public string? MahalleAdi { get; set; }
        public string? CaddeAdi { get; set; }
        public string? IlceAdi { get; set; }
        public int? GidenSubeId { get; set; }
        public int? GidenPostaId { get; set; }
        public int? BildirimTuru { get; set; }
        public int? SondurmeKopukAff { get; set; }
        public int? SondurmeKopukAlkol { get; set; }
        public int? SondurmeKopukSentetik { get; set; }
        public int? DogalAfetTuru { get; set; }
        public int? SolunumSeti { get; set; }
        public int? PersonelSayisi { get; set; }
        public int? YrdEkipPersonelSayisi { get; set; }
        public string? KurtarmaSekli { get; set; }
        public string? YanginBaslangicNedeni { get; set; }
        public int? KayitNo { get; set; }
        public DateTime? RaporKayitTarihi { get; set; }
        public DateTime? KayitTarihi { get; set; }
        public int? GidenEkipPersonelSayisi { get; set; }
        public int? YardimciEkipPersonelSayisi { get; set; }
        public int? GidenEkipAracSayisi { get; set; }
        public int? YardimciEkipAracSayisi { get; set; }
        public int? RaporOlu { get; set; }
        public int? RaporYarali { get; set; }
        public int? OluItfaiyeciSayisi { get; set; }
        public int? YaraliItfaiyeciSayisi { get; set; }
        public int? OluHalkSayisi { get; set; }
        public int? YaraliHalkSayisi { get; set; }
        public int? OluKadinSayisi { get; set; }
        public int? OluErkekSayisi { get; set; }
        public int? OluCocukSayisi { get; set; }
        public int? YaraliKadinSayisi { get; set; }
        public int? YaraliErkekSayisi { get; set; }
        public int? YaraliCocukSayisi { get; set; }
        public int? KurtarmaTuruCinsi { get; set; }
        public string? KurtarmaTuruCinsiTxt { get; set; }
        public int? KayitSilindi { get; set; }
        public string? SahibiUyrukAciklama { get; set; }
        public int? SahibiUyruk { get; set; }
        public string? KiraciVeyaKullananUyrukAciklama { get; set; }
        public int? KiraciVeyaKullananUyruk { get; set; }
        public int? RaporKayitNoOlusturan { get; set; }
        public DateTime? RaporKayitNoOlusturmaTarihi { get; set; }
        public string? YanginNobetciCavusuTxt { get; set; }
        public string? YanginNobetciCavusuGoreviTxt { get; set; }
        public string? GidenEkibinAmiriGoreviTxt { get; set; }
        public int? KazayaKarisanAracSayisi { get; set; }
        public int? EngelliSayisi { get; set; }
        public string? OnaylayanTxt { get; set; }
        public string? OnaylayanGoreviTxt { get; set; }
        public string? IlceId { get; set; }
        public string? MahalleId { get; set; }
        public string? CsbmId { get; set; }
        public string? SahibiTc { get; set; }
        public string? KiraciVeyaKullananTc { get; set; }
    }
}
